### ISSUE TITLE
This application has no explicit mapping for /error, so you are seeing this as a fallback.

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-lodview#21]
## I expect

Executing the application via the following compose, to  work (you can ignore the truststore settings, that is required because java does not trust schema.gov.it TLS certificate).

```
version: '3.9'
services:
  lodview:
    build: .
    user: "1001:1001"
    environment:
      - LodViewendpoint=https://schema.gov.it/sparql
    volumes:
      - .:/code:z
    command: [
      "java",
      "-Djavax.net.ssl.trustStore=/code/test/truststore.jks",
      "-Djavax.net.ssl.trustStorePassword=changeit",
      "-jar",
      "/app/lodview.jar"
      ]
```

## Comportamento attuale

It doesn't. The behavior is the same as on https://lod-ndc-dev.apps.cloudpub.testedev.istat.it/

## Notes

While adding `working_dir: /code` works

```
version: '3.9'
services:
  lodview:
    build: .
    user: "1001:1001"
    environment:
      - LodViewendpoint=https://schema.gov.it/sparql
    volumes:
      - .:/code:z
    working_dir: /code
    command: [
      "java",
      "-Djavax.net.ssl.trustStore=/code/test/truststore.jks",
      "-Djavax.net.ssl.trustStorePassword=changeit",
      "-jar",
      "/app/lodview.jar"
      ]
```

**Comment by ioggstream** [comment]
Stracing the container, I get

```
$ sudo strace -f -e file -p 2351814
strace: Process 2351814 attached with 41 threads
[pid 2351907] lstat("/tmp/tomcat-docbase.8080.11621927043943193187", {st_mode=S_IFDIR|0700, st_size=6, ...}) = 0
[pid 2351907] lstat("/tmp/tomcat-docbase.8080.11621927043943193187/WEB-INF", 0x7f5fddca3bf0) = -1 ENOENT (File o directory non esistente)
```

**Comment by gnespolino** [comment]
This issue is also reproducible by:

- compiling sources (i.e. `./gradlew clean build`)
- copy the resulting jar file somewhere else (i.e. `cp build/lib/lodview.jar /tmp)
- running from there (i.e. `cd /tmp && java -jar lodview.jar)

it happens because the jar packaging doesn't bundle JSP pages within the archive.

To address this issue we should switch package to WAR.
