### ISSUE TITLE
dct:modified date

### ISSUE THREAD

**Issue by giorgialodi** [teamdigitale/dati-semantic-lodview#24]
## Comportamento atteso
Visualizzare solo l'ultima data di modifica. Così come è ora su AGID. 
<img width="1277" alt="Screenshot 2022-11-21 at 13 55 10" src="https://user-images.githubusercontent.com/24624577/203060763-6e246e26-e787-4f89-952b-776235c98d07.png">

## Comportamento attuale
vedo più date separate da ... da dove nasce questa cosa?

<img width="1274" alt="Screenshot 2022-11-21 at 13 51 08" src="https://user-images.githubusercontent.com/24624577/203060779-2c1160fd-0596-45c7-9012-affb1481b927.png">

## Possibili soluzioni
bisogna prendere solo l'ultima istanza di dct:modified.

## Contesto
sto usando firefox

**Comment by gnespolino** [comment]
@giorgialodi il comportamento attuale, cioè la presenza di 2 `modified`, deriva direttamente dal contenuto su sparql:

su AGID:
https://ontopia-virtuoso.agid.gov.it/sparql?default-graph-uri=&query=select+distinct+%3Fprop+%3Fvalue+where+%7B+%3Chttps%3A%2F%2Fw3id.org%2Fitalia%2Fonto%2FCPV%3E+%3Fprop+%3Fvalue%7D&format=text%2Fhtml&should-sponge=&timeout=0&signal_void=on

su NDC-TEST:
https://virtuoso-test-external-service-ndc-test.apps.cloudpub.testedev.istat.it/sparql?default-graph-uri=&query=select+distinct+%3Fprop+%3Fvalue+where+%7B+%3Chttps%3A%2F%2Fw3id.org%2Fitalia%2Fonto%2FCPV%3E+%3Fprop+%3Fvalue%7D&format=text%2Fhtml&timeout=0&signal_void=on

**Comment by giorgialodi** [comment]
ciao @gnespolino allora la domanda è: come mai c'è un doppio valore su NDC test della stessa proprietà? Tra l'altro se guardo il sorgente su github vedo solo una data dct:modified https://github.com/italia/daf-ontologie-vocabolari-controllati/blob/master/Ontologie/CPV/latest/CPV-AP_IT.ttl 
È da capire quello. Pensavo corrispondesse a dct:issued ma no, non è nemmeno quello.  Online su schema.gov.it c'è una sola data di modifica. 
L'anomalia  è la doppia proprietà dct:modified che si trova nello sparql endpoint NDC-test.

**Comment by gnespolino** [comment]
@giorgialodi non ne ho idea, dovremo guardare il codice dell'harvester per capire.

**Comment by giorgialodi** [comment]
@gnespolino facendo un giro qui: https://lod-ndc-dev.apps.cloudpub.testedev.istat.it/lodview/onto/CPV il problema sembra non esserci più. Non so se avete fatto qualcosa ma se sì, probabilmente avete sistemato l'anomalia nello sparql endpoint di test. Chiudo l'issue. Se si dovesse ripresentare lo riapriamo :)
