### ISSUE TITLE
Configure the welcome page / welcome text

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-lodview#26]
## I expect

the welcome page to contain NDC-specific text cc: @Clou-dia 

## Instead

it contains "lorem ipsum"

## Notes

- describe in this ticket the procedure for updating the welcome page
- document how it is possible to provide the welcome text via a configuration content using kubernetes in dati-semantic-kubernetes

**Comment by ioggstream** [comment]
cc: @gnespolino

**Comment by nnzJd** [comment]
Created 3 new conf variables to set welcome text via env variables in dati-semantic-kubernetes: 
1. `LodViewhomeTitle`
2. `LodViewhomeDescription`
3. `LodViewhomeContent`

`LodViewhomeTitle` will set :
![image](https://user-images.githubusercontent.com/37577928/205327770-d79cdaca-e7e9-4c16-8e3d-7a841d26ec14.png)

`LodViewhomeDescription` will set:
![image](https://user-images.githubusercontent.com/37577928/205328193-f80230c6-26a5-4ed6-a17c-fb183458abd9.png)

`LodViewhomeContent` will set:
![image](https://user-images.githubusercontent.com/37577928/205328429-65a6e320-d57b-4375-826e-8f78975af044.png)


Need to define the correct values in kubernetes.

cc: @ioggstream

**Comment by Clou-dia** [comment]
The text expected is

![Home_lodview](https://user-images.githubusercontent.com/98462345/206679671-b2b24b5a-4bd2-4587-8a7e-d6d1d98f9028.png)

if possibile change the color background in #F0F6FC

[titolo]
Il catalogo nazionale per l'interoperabilità semantica
H1 - Display 1/lg - font Titillium web - Bold - font size 48px - font color #1A1A1A

[sottotitolo]
Schema è il catalogo in continua evoluzione, che armonizza e standardizza i modelli di dati condivisi e garantisce che formato e significato delle informazioni scambiate siano preservati e compresi durante gli scambi.
Questo strumento consente la navigazione web dei contenuti delle ontologie e dei vocabolari controllati per la pubblica amministrazione.
H2 - lead/lg - font Titillium web - regular - font size 24px - font color #1A1A1A


--------
![Home_lodview_v2](https://user-images.githubusercontent.com/98462345/206681008-7e20da5b-f191-46cd-a2f0-2707d4c0379d.png)

if not possible to change the color background 

[titolo]
Il catalogo nazionale per l'interoperabilità semantica
H1 - Display 1/lg - font Titillium web - Bold - font size 48px - font color #FFFFFF

[sottotitolo]
Schema è il catalogo in continua evoluzione, che armonizza e standardizza i modelli di dati condivisi e garantisce che formato e significato delle informazioni scambiate siano preservati e compresi durante gli scambi.
H2 - lead/lg - font Titillium web - regular - font size 24px - font color #FFFFFF

[testo]
Questo strumento consente la navigazione web dei contenuti delle ontologie e dei vocabolari controllati per la pubblica amministrazione.
H2 - lead/lg - font Titillium web - regular - font size 24px - font color #1A1A1A


![Home_lodview_v2](https://user-images.githubusercontent.com/98462345/206681008-7e20da5b-f191-46cd-a2f0-2707d4c0379d.png)
