### ISSUE TITLE
Remove reference to external libraries, fonts and code

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/dati-semantic-lodview#27]
## I expect

- the app does not rely on external fonts and code
- style is aligned with design kit cc: @Clou-dia 

## Instead

- it loads fonts and js from CDNs

## Notes

- can this be configured in some way?

**Comment by gnespolino** [comment]
@ioggstream regarding external fonts loading, this is something internal in jquery library, so it's hard to fix

**Comment by ioggstream** [comment]
@Clou-dia how did we fix this issue in other projects?

**Comment by ioggstream** [comment]
@gnespolino pls always cc: @mfortini  
for design/accessibility stuff, cc: @Clou-dia too
thx++ :)

**Comment by Fupete** [comment]
We load them locally, not via Google. See Bootstrap Italia [docs ](https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/#fonts), here the [folder](https://github.com/italia/bootstrap-italia/tree/main/src/fonts).
